apiVersion: v1
kind: Template
labels:
  template: rshiny-authproxy
  app: '${PROJECT}-${COMPONENT}'
parameters:
- description: The name of the application project.
  displayName: Project
  name: PROJECT
  required: true
- description: The name of the component
  displayName: Component
  name: COMPONENT
  required: true
- description: The environment stage.
  displayName: Environment
  name: ENV
  required: true
- description: Authantication Realm
  displayName: Name of Authantication Realm for users.
  name: CROWD_RSHINY_REALM_NAME
  required: true
- description: Crowd authentication service URL
  displayName: Crowd service URL
  name: CROWD_URL
  required: true
objects:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: ${COMPONENT}-authproxy
  spec:
    ports:
    - name: 80-tcp
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: ${COMPONENT}-authproxy
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 1
    name: ${COMPONENT}-authproxy
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      name: ${COMPONENT}-authproxy
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: ${COMPONENT}-authproxy
      spec:
        containers:
        - env:
          - name: SERVICE
            value: ${COMPONENT}.${PROJECT}-${ENV}.svc.cluster.local
          - name: SERVER_SIGNATURE
            value: ${PROJECT}-${COMPONENT}
          - name: WAF_MODSECURITY
            value: "off"
          - name: CROWD_REALM_NAME
            value: ${CROWD_RSHINY_REALM_NAME}
          - name: CROWD_URL
            value: ${CROWD_URL}
          - name: CROWD_SERVICE
            valueFrom:
              secretKeyRef:
                name: crowd-service
                key: username
          - name: CROWD_PASSWORD
            valueFrom:
              secretKeyRef:
                name: crowd-service
                key: password
          name: ${COMPONENT}-authproxy
          image: shared-services/nginx-authproxy:3.0
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${COMPONENT}-authproxy
        from:
          kind: ImageStreamTag
          namespace: shared-services
          name: 'nginx-authproxy:3.0'
      type: ImageChange
  status: {}
