apiVersion: v1
kind: Template
labels:
  template: component-route-template
  app: ${PROJECT}
  component: ${COMPONENT}
  env: ${ENV}
metadata:
  annotations:
    description: |-
      This templates performs the setup or a route for a component.
    iconClass: icon-nodejs
    openshift.io/display-name: Component Template
    template.openshift.io/long-description: This template defines a route for a component.
  name: component-route
objects:
  - apiVersion: v1
    kind: Route
    metadata:
      name: ${COMPONENT}
    spec:
      host: ${COMPONENT}-${PROJECT}-${ENV}.${OD_OCP_SOURCE_APP_DOMAIN}
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${COMPONENT}
        weight: 100
      wildcardPolicy: None
parameters:
- description: The name of the application project.
  displayName: Project
  name: PROJECT
  required: true
- description: The environment stage.
  displayName: Environment
  name: ENV
  required: true
- description: The name of the component
  displayName: Component
  name: COMPONENT
  required: true
- description: The application domain
  displayName: app domain
  name: OD_OCP_SOURCE_APP_DOMAIN
  required: true
