FROM cd/jenkins-slave-scala

MAINTAINER "Clemens Utschig" <clemens.utschig-utschig@boehringer-ingelheim.com>

WORKDIR /data

ENV HOME=/home/jenkins
ENV SBT_CREDENTIALS="/home/jenkins/.sbt/credentials"

ENTRYPOINT [""]
