apiVersion: v1
kind: Template
metadata:
  annotations: {}
  creationTimestamp: null
  name: jenkins-slave-nodejs10-angular
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations: {}
    creationTimestamp: null
    name: jenkins-slave-nodejs10-angular
    labels:
      app: jenkins-slave-nodejs10-angular
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: jenkins-slave-nodejs10-angular:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: jenkins-slaves/nodejs10-angular
      git:
        ref: production
        uri: ${REPO_BASE}/opendevstack/ods-project-quickstarters.git
      sourceSecret:
        name: cd-user-token
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile.rhel7
        env:
          - name: NEXUS_HOST
            value: ${NEXUS_URL}
          - name: NEXUS_AUTH
            value: ${NEXUS_AUTH}
        from:
          kind: ImageStreamTag
          name: jenkins-slave-base:latest
      type: Docker
    triggers: []
parameters:
- name: NEXUS_URL
  required: true
- name: NEXUS_AUTH
  required: true
- name: REPO_BASE
  required: true
