apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: rshiny-app
objects:
- apiVersion: v1
  data:
    password: ${CROWD_RSHINY_REALM_PW}
    username: ${CROWD_RSHINY_REALM_USER}
  kind: Secret
  metadata:
    creationTimestamp: 2017-06-29T19:42:06Z
    name: crowd-service
    namespace: ${PROJECT}-${ENV}
  type: kubernetes.io/basic-auth
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    labels:
      app: ${PROJECT}
      component: ${COMPONENT}
      env: ${ENV}
    name: ${COMPONENT}
  spec:
    dockerImageRepository: ${COMPONENT}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      project: ${PROJECT}
      component: ${COMPONENT}
      environment: ${ENV}
    name: ${COMPONENT}
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${COMPONENT}:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: ${BITBUCKET_URL}
      sourceSecret:
        name: cd-user-token
      type: Git
    strategy:
      dockerStrategy: {}
      type: Docker
    triggers:
      - type: Generic
        generic:
          secret: ${TRIGGER_SECRET}
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 1
    name: ${COMPONENT}
  spec:
    replicas: 1
    selector:
      name: ${COMPONENT}
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: ${COMPONENT}
      spec:
        containers:
        - env:
          name: ${COMPONENT}
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${COMPONENT}
        from:
          kind: ImageStreamTag
          name: ${COMPONENT}:latest
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 1
    name: ${COMPONENT}-authproxy
  spec:
    replicas: 1
    selector:
      name: ${COMPONENT}-authproxy
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: ${COMPONENT}-authproxy
      spec:
        containers:
        - env:
          - name: SERVICE
            value: ${COMPONENT}.${PROJECT}-${ENV}.svc.cluster.local
          - name: CROWD_REALM_NAME
            value: ${CROWD_REALM_NAME}
          - name: CROWD_URL
            value: ${CROWD_URL}
          - name: CROWD_SERVICE
            valueFrom:
              secretKeyRef:
                name: crowd-service
                key: username
          - name: CROWD_PASSWORD
            valueFrom:
              secretKeyRef:
                name: crowd-service
                key: password
          name: ${COMPONENT}-authproxy
          image: shared-services/nginx-authproxy:1.0
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${COMPONENT}-authproxy
        from:
          kind: ImageStreamTag
          namespace: shared-services
          name: 'nginx-authproxy:1.0'
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: ${PROJECT}
      component: ${COMPONENT}
      env: ${ENV}
    name: ${COMPONENT}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: ${COMPONENT}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: ${COMPONENT}-authproxy
    name: ${COMPONENT}-authproxy
  spec:
    ports:
    - name: 80-tcp
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: ${COMPONENT}-authproxy
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      app: ${COMPONENT}-authproxy
    name: ${COMPONENT}
  spec:
    port:
      targetPort: 80-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: ${COMPONENT}-authproxy
      weight: 100
    wildcardPolicy: None
parameters:
- description: The name of the application project.
  displayName: Project
  name: PROJECT
  required: true
- description: The name of the component
  displayName: Component
  name: COMPONENT
  required: true
- description: The environment stage.
  displayName: Environment
  name: ENV
  required: true
- description: The bitbucket URL  
  displayName: Bitbucket URL
  name: BITBUCKET_URL
  required: true
- description: Trigger secret
  name: TRIGGER_SECRET
  value: secret101
- description: Authantication Realm
  displayName: Name of Authantication Realm for users.
  name: CROWD_REALM_NAME
  value: CROWD_RSHINY_REALM_NAME
- description: Crowd authentication service URL
  displayName: Crowd service URL
  name: CROWD_URL
  value: CROWD_URL
- description: Authentication Crowd user
  displayName: crowd user
  name: CROWD_RSHINY_REALM_USER
  value: CROWD_RSHINY_REALM_USER
- description: Authentication Crowd pw
  displayName: crowd pw
  name: CROWD_RSHINY_REALM_PW
  value: CROWD_RSHINY_REALM_PW
