apiVersion: v1
kind: Template
labels:
  template: component-template
  app: '${PROJECT}-${COMPONENT}'
metadata:
  annotations:
  name: bc-docker
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Defines how to build the application
    name: ${COMPONENT}
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${COMPONENT}:${TAGVERSION}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      type: Binary
      binary: {}
    strategy:
      type: Docker
      dockerStrategy: {}
    successfulBuildsHistoryLimit: 5
    triggers: []
parameters:
- description: The name of the application project.
  displayName: Application
  name: PROJECT
  required: true
- description: The name of the application component.
  displayName: Component
  name: COMPONENT
  required: true
- description: The environment stage.
  displayName: Environment
  name: ENV
  required: true
- description: The version to be used.
  displayName: tag version
  name: TAGVERSION
  required: true
