apiVersion: v1
kind: Template
labels:
  template: component-template
  app: '${PROJECT}'
  branch: '${BRANCH}'
  component: '${COMPONENT}'
  env: '${ENV}'
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        description: Exposes and load balances the application pods
        service.alpha.openshift.io/dependencies: '[]'
      name: '${COMPONENT}'
    spec:
      ports:
      -   name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: '${PROJECT}'
        component: '${COMPONENT}'
        deploymentconfig: '${COMPONENT}'
        env: '${ENV}'
      sessionAffinity: None
      type: ClusterIP
parameters:
  - name: PROJECT
    displayName: Application
    description: The name of the application project.
    required: true
  - name: COMPONENT
    displayName: Component
    description: The name of the application component.
    required: true
  - name: ENV
    displayName: Environment
    description: The environment stage.
    required: true
  - name: BRANCH
    displayName: Branch
    description: The branch (either 'feature' or 'master').
    value: feature
    required: true
