def final projectId = '@project_id@'
def final componentId = '@component_id@'
def final groupId = '@group_id@'
def final credentialsId = "${projectId}-cd-cd-user-with-password"
def sharedLibraryRepository
def dockerRegistry
node {
  sharedLibraryRepository = env.SHARED_LIBRARY_REPOSITORY
  dockerRegistry = env.DOCKER_REGISTRY
}

library identifier: 'ods-library@latest', retriever: modernSCM(
  [$class: 'GitSCMSource',
   remote: sharedLibraryRepository,
   credentialsId: credentialsId])

// See readme of shared library for usage and customization.
odsPipeline(
  image: "${dockerRegistry}/cd/jenkins-slave-nodejs8-angular",
  projectId: projectId,
  componentId: componentId,
  groupId: groupId,
  verbose: true
) { context ->
  stageBuild(context)
  stageUnitTest(context)
  stageLint(context)
  stageScanForSonarqube(context)
  stageUploadToNexus(context)
  stageCreateOpenshiftEnvironment(context)
  stageUpdateOpenshiftBuild(context)
  stageDeployToOpenshift(context)
  stageTriggerAllBuilds(context)
}

def stageBuild(def context) {
  stage('Build') {
    withEnv(["TAGVERSION=${context.tagversion}"]) {
      sh "yarn global add ionic@3.19.0"
      sh "yarn install"
      if ('master'.equals(context.gitBranch)) {
        sh "npm run ionic:build --prod"
      } else {
        sh "npm run ionic:build"
      }
    }
    archiveBuild(context)
  }
}

def stageUnitTest(def context) {
    stage('Unit Test') {
      sh "yarn test -- --single-run --progress false"
    }
}

def stageLint(def context) {
  stage('Lint') {
    sh "npm run lint"
  }
}

def archiveBuild(def context) {
  def buildTimestamp = new Date().format("dd.MM.yyyy-HH:mm", TimeZone.getTimeZone('UTC'))
  writeFile file: 'dist/version.json', text: """
            {
              \"tagVersion\": \"${context.tagversion}\",
              \"gitCommit\": \"${context.gitCommit}\",
              \"buildTimestamp\": \"${buildTimestamp}\"
            }"""
  def distFile = "${context.componentId}-${context.tagversion}.tar.gz"
  sh "tar czvf ${distFile} -C www ."
}
