/* generated jenkins file used for building and deploying @component_id@ in projects @project_id@ */
def final projectId = '@project_id@'
def final componentId = '@component_id@'
def final credentialsId = "${projectId}-cd-cd-user-with-password"
def sharedLibraryRepository
def dockerRegistry
def trainingRoute
def trainingPodInfo
def trainingPassword
def trainingUsername

def trainingConfig = [
    "docker-training"  : "${componentId}-training-service",
]

def predictionConfig = [
    "docker-prediction": "${componentId}-prediction-service"
]

node {
    sharedLibraryRepository = env.SHARED_LIBRARY_REPOSITORY
    dockerRegistry = env.DOCKER_REGISTRY
}

library identifier: 'ods-library@1.1.x', retriever: modernSCM(
    [$class       : 'GitSCMSource',
        remote       : sharedLibraryRepository,
        credentialsId: credentialsId])

// See readme of shared library for usage and customization.
odsPipeline(
    image: "${dockerRegistry}/cd/jenkins-slave-python",
    projectId: projectId,
    componentId: componentId,
    openshiftBuildTimeout: 25,
    branchToEnvironmentMapping: [
        'master': 'test',
        '*'     : 'dev'
    ]
) { context ->
    stageScanForSonarqube(context)
    stageBuild(context)
    stageStartMultipleOpenshiftBuild(context, "Build Training Image" ,trainingConfig)
    stageMultipleDeployToOpenshift(context, "Deploy Training Pod", trainingConfig)
    stageUnitTestsTraining(context)
    stageTraining(context)
    stageIntegrationTestTraining(context)
    stageStartMultipleOpenshiftBuild(context, "Build Prediction Image", predictionConfig)
    stageMultipleDeployToOpenshift(context, "Deploy Prediction Pod", predictionConfig)
}

def stageLinter(def context) {
    stage('Linter') {
        // PEP8
        sh '''
pycodestyle --show-source --show-pep8 src/*
pycodestyle --statistics -qq src/*
  '''
    }
}


def stageUnitTestsTraining(def context) {
    stage('Unittests') {
        trainingPodInfo = sh(returnStdout: true, script:"sleep 5 && oc get pods --sort-by=.status.startTime --no-headers -n ${context.targetProject} | grep ${context.componentId}-training-service | tail -n1").trim().split(/\s+/)
        print("Found pod name: ${trainingPodInfo[0]}")
        if (trainingPodInfo[2] == "Running") {
            sh(returnStdout: true, script: " oc project ${context.targetProject} && oc exec ${trainingPodInfo[0]} bash ./run_unittests.sh ")
        }
    }
}


def stageBuild(def context) {
    stage('Prepare Docker Builds') {
        sh './build.sh'
    }
}

def stageTraining(def context) {
    stage('Train Model') {
        sh(returnStdout: true, script:"pip install -i ${context.nexusHostWithBasicAuth}/repository/pypi-all/simple requests --user")

        trainingRoute = "http://localhost:8080"

        trainingPassword = sh(returnStdout: true, script:"oc get secret ${context.componentId}-training-secret -o yaml -n ${context.targetProject} | grep password: | cut -d':' -f2 ").trim()
        trainingUsername = sh(returnStdout: true, script:"oc get secret ${context.componentId}-training-secret -o yaml -n ${context.targetProject} | grep username: | cut -d':' -f2 ").trim()
        trainingPassword = sh(returnStdout: true, script:"echo \"${trainingPassword}\" | base64 --decode").trim()
        trainingUsername = sh(returnStdout: true, script:"echo \"${trainingUsername}\" | base64 --decode").trim()

        sh "oc port-forward ${trainingPodInfo[0]} 8080 -n ${context.targetProject} &"
        sh  "python3 jenkinsfile_helper.py --training-service ${trainingRoute} --username \"${trainingUsername}\" --password \"${trainingPassword}\""
    }
}


def stageIntegrationTestTraining(def context) {
    stage('Integration Tests') {
        trainingPodInfo = sh(returnStdout: true, script:"sleep 5 && oc get pods --sort-by=.status.startTime --no-headers -n ${context.targetProject} | grep ${context.componentId}-training-service | tail -n1").trim().split(/\s+/)
        print("Found pod name: ${trainingPodInfo[0]}")
        if (trainingPodInfo[2] == "Running") {
            sh(returnStdout: true, script: " oc project ${context.targetProject} && oc exec ${trainingPodInfo[0]} bash ./run_integration_tests.sh ")
        }
        print("Pod ${trainingPodInfo[0]} is not running... cannot execute integration tests")
    }
}


def stageStartMultipleOpenshiftBuild(def context, def stageName, def buildConfigs = null) {
    if (buildConfigs != null) {
        stage(stageName) {
            if (!context.environment) {
                println("Skipping for empty environment ...")
                return
            }
            buildConfigs.each { dockerFolder, buildConfig ->
                timeout(context.openshiftBuildTimeout) {
                    patchBuildConfig(context, buildConfig)
                    sh "oc start-build  --from-dir ${dockerFolder} --follow -n ${context.targetProject} " +
                    "${buildConfig}"
                }
            }
        }
    } else {
        stageStartOpenshiftBuild(context)
    }
}

private void patchBuildConfig(def context, def componentId = null) {
    sh """oc patch bc ${componentId ?: context.componentId} --type=json --patch '[
    {"op": "replace", "path": "/spec/source", "value":{"type":"Binary"}},
    {"op": "replace", "path": "/spec/output/to/name", "value":"${componentId ?: context.componentId}:${
        context.tagversion
    }"},
    {"op": "replace", "path": "/spec/strategy/dockerStrategy", "value":{"buildArgs":[
            {"name": "nexusHostWithBasicAuth" ,"value": "${context.nexusHostWithBasicAuth}"},
            {"name": "nexusHostWithoutScheme" ,"value": "${context.nexusHost.tokenize('//')[1]}"}
        ]}},
    ]' -n ${context.targetProject}"""
}

def stageMultipleDeployToOpenshift(def context, def stageName, def buildConfigs = null) {
    if (buildConfigs != null) {
        stage(stageName) {
            if (!context.environment) {
                println("Skipping for empty environment ...")
                return
            }
            buildConfigs.each { dockerFolder, buildConfig ->
                openshiftTag(
                        srcStream: buildConfig,
                        srcTag: context.tagversion,
                        destStream: buildConfig,
                        destTag: "latest",
                        namespace: context.targetProject
                )
            }
        }
    } else {
        stageDeployToOpenshift(context)
    }
    while(true) {
    trainingPodInfo = sh(returnStdout: true, script:"sleep 5 && oc get pods --sort-by=.status.startTime --no-headers -n ${context.targetProject} | grep ${context.componentId}-training-service | tail -n1").trim().split(/\s+/)
    print("Found pod name: ${trainingPodInfo[0]}")
    if (trainingPodInfo[2] == "Running") {
        print("Pod ${trainingPodInfo[0]} is running!!!")
        break
    }
    print("Pod ${trainingPodInfo[0]} is still not running...")
    }
}
