apiVersion: v1
kind: Template
labels:
  template: rshiny-secrets
parameters:
- description: Authentication Crowd user
  displayName: crowd user
  name: CROWD_RSHINY_REALM_USER
  required: true
- description: Authentication Crowd pw
  displayName: crowd pw
  name: CROWD_RSHINY_REALM_PW
  required: true
- name: NEXUS_PASSWORD
  value: NEXUS_PASSWORD
  required: true
objects:
  - apiVersion: v1
    data:
      password: '${NEXUS_PASSWORD}'
    kind: Secret
    metadata:
      name: nexus
    type: opaque
  - apiVersion: v1
    data:
      password: ${CROWD_RSHINY_REALM_PW}
      username: ${CROWD_RSHINY_REALM_USER}
    kind: Secret
    metadata:
      name: crowd-service
    type: kubernetes.io/basic-auth

